language: go

go:
  - 1.17.x

os: linux

dist: xenial

services:
  - docker

before_install:
  - go mod download

script:
  - make all-tests lint
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)