language: go

go:
  - 1.17.x

before_install:
  - go mod download
  - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0

script:
  - make all-tests lint
  - golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)